### ISSUE TITLE
Doesn't work for A13 on iOS 13.4? 

### ISSUE THREAD

**Issue by xxhhlk** [Hoangdus/Speedster#6]
As the title suggests, I have an iPhone SE (2nd generation) running iOS 13.4, and I just installed your tweak, Speedster.
However, I found that it does not work on the Springboard and system-built apps. Additionally, the settings cannot be loaded ,the error message is: "There was an error loading the preference bundle for Speedster". I can only see the settings using "Tweak Settings."
I hope you can fix this. If you need logs, please let me know how to view them, and I will provide them. Thank you!

**Comment by Hoangdus** [comment]
Sorry for the late reply, this is a known issue and will be fixed in the next update in the near future

**Comment by Hoangdus** [comment]
This should be fixed in [Update 2.1.0](https://github.com/Hoangdus/Speedster/releases/tag/2.1.0)

**Comment by xxhhlk** [comment]
Hello,

Thank you for the update to version 2.1.0. Now the preference bundle can be loaded, but it seems that the changes made in the settings are not taking effect; they are not being applied globally. Additionally, the Respring button at the bottom of the settings also does not respond. I have manually respring several times, but the issue persists. Could there be a problem with my settings? Also, my iOS version is 13.4.1, I apologize for the earlier mistake, and I hope this does not affect anything.
![IMG_0097](https://github.com/Hoangdus/Speedster/assets/15075327/b0e88c6c-2681-4ea9-90bf-dd4c5fb8a911)

**Comment by Hoangdus** [comment]
@xxhhlk everything should be fixed now in [2.1.1](https://github.com/Hoangdus/Speedster/releases/tag/2.1.1)

**Comment by xxhhlk** [comment]
Great news, everything's sorted now! Thanks a bunch!

**Comment by xxhhlk** [comment]
Hi @Hoangdus , Sorry for the late response! It seems version 2.1.2 brought back the exact same issue as version 2.1.0.

The preference bundle loads fine, but changes are not taking effect globally, and the Respring button at the bottom still doesn't respond.

Could you please take a look when you have time? Reopening this issue for tracking. Thanks!
